server {
    listen 443 ssl;
    http2 on;

    listen 443 quic reuseport;

    server_name de.7apri.cfd;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location /api/auth/ {
        limit_req zone=auth_limit burst=5 nodelay;
        limit_req_status 429;
        proxy_pass http://server:8080;
    }

    location = /api/ws {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://server:8080;
    }

    location /static/ {
        alias /var/www/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location = /favicon.ico {
        root /var/www/static/assets;
        try_files /favicon.svg =404;
        access_log off;
    }

    error_page 404 /error_404;
    location = /error_404 {
        internal;
        return 404 "Not Found";
    }

    error_page 429 /error_429;
    location = /error_429 {
        internal;
        default_type application/json;
        return 429 "{\"code\":\"err:too_many_requests\"}";
    }

    location / {
        proxy_pass http://server:8080;
    }
}
