FROM golang:1.25.5-alpine AS builder

WORKDIR /server

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server ./cmd/server

FROM alpine:latest

WORKDIR ./site
COPY --from=builder /server/server .
COPY --from=builder /server/public .

CMD ["./server"]