limit_req_zone $http_cf_connecting_ip zone=auth_limit:10m rate=1r/s;

map $status $loggable {
    ~^[23]  0;
    default 1;
}

server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types 
        text/plain 
        text/css 
        application/json 
        application/javascript 
        text/xml 
        application/xml 
        application/xml+rss 
        text/javascript 
        image/svg+xml 
        image/x-icon;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "no-referrer-when-downgrade";

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    
    proxy_set_header X-Real-IP $http_cf_connecting_ip;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    msie_padding off;
    recursive_error_pages off;

    access_log /var/log/nginx/access.log combined if=$loggable;

    error_page 404 = /error_404;
    error_page 429 = /error_429;

    location /api/auth/ {
        limit_req zone=auth_limit burst=5 nodelay;
        limit_req_status 429;
        proxy_pass http://server:8080;
    }

    location /static/ {
        root /var/www;
        error_page 404 = /error_404;
    }
    location = /favicon.ico {
        root /var/www/static/assets;
        
        try_files /favicon.svg =404;

        access_log off;
        log_not_found off;
    }

    location = /error_404 {
        internal;
        default_type text/plain;
        return 404 "Not Found";
    }

    location = /error_429 {
        internal;
        default_type application/json;
        return 429 "{\"error\": \"Rate limit exceeded\"}";
    }

    location / {
        proxy_pass http://server:8080;
    }
}
