user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;

    #map $http_cf_connecting_ip $client_ip {
    #    ""      $remote_addr;
    #    default $http_cf_connecting_ip;
    #}

    map $request_uri $loggable {
        ~*\.(css|js|png|jpg|gif|ico|svg|webp)$ 0;
        default 1;
    }

    log_format custom_json escape=json '{'
        '"time": "$time_iso8601",'
        '"ip": "$remote_addr",'
        '"status": "$status",'
        '"rt": "$request_time",'
        '"urt": "$upstream_response_time",'
        '"req": "$request",'
        '"ua": "$http_user_agent"'
    '}';

    access_log /var/log/nginx/access.log custom_json buffer=32k flush=5s if=$loggable;

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml image/svg+xml;
    brotli_types text/plain text/css application/json application/javascript text/xml image/svg+xml;

    ssl_certificate /etc/letsencrypt/live/de.7apri.cfd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/de.7apri.cfd/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=1r/s;

    server {
        listen 80;
        
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/letsencrypt;
            allow all;
            default_type "text/plain";
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
    
    include /etc/nginx/conf.d/*.conf;
}